name: no_cpu
description: A framework for no-CPU Amiga demos.
version: 1.0.0
repository: https://github.com/askeksa/NoCpuChallenge

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1
  path: ^1.9.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
